url: https://matling.fit
baseurl: "/"
title: 物灵

show_excerpts: true
permalink: /blog/:title:output_ext
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/blog/:num"

theme-2038:
  drawer-links:
    -
      name:
        cmn: 主站
        lzh: 卷首
        en: Home
        tok: lipu open
      url: /
    -
      name:
        cmn: 博文
        lzh: 全覧
        cmn-Latn: Bówén
        en: Blog
        tok: lipu ali
      url: /blog
    -
      name:
        cmn: 含章字典
        lzh: 含章字典
        cmn-Latn: Hánzhāng Zìdiǎn
        en: Lexicon
        tok: nimi Malin
      url: https://lex.matling.fit
    -
      name:
        cmn: 关于
        lzh: 自敘
        en: About
        tok: mi seme
      url: /blog/about
    -
      name:
        cmn: 他山
        lzh: 他山
        cmn-Latn: Tāshān
        en: Friends
        tok: jan pona
      url: /blog/friends
    -
      name:
        cmn: 异次元之旅 ☈
        en: Go Wild ☈
        tok: tawa suli ☈
        lzh: 雲闥 ☈
      url: https://travel.moe/go.html
