url: https://matling.fit
baseurl: "/"
title: 物灵

show_excerpts: true
permalink: /blog/:title:output_ext
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/blog/:num"

theme-2038:
  drawer-links:
    -
      name:
        cmn: 博文
        lzh: 吟草
        en: Blog
        tok: lipu ali
        dng: Зуəвын
        art-x-mini: Note
      url: /blog
    -
      name:
        cmn: 含章字典
        lzh: 含章字典
        en: Lexicon
        tok: nimi Malin
        dng: Ханҗон хуадян
        art-x-mini: Buku-name
      url: https://lex.matling.fit
    -
      name:
        cmn: 关于
        lzh: 自敘
        en: About
        tok: mi seme
        dng: Сыйҗяди
        art-x-mini: Ego
      url: /blog/about
    -
      name:
        cmn: 他山
        lzh: 訪舊
        wuu: 朋友家
        en: Friends
        tok: jan pona
        dng: Тамыр
        art-x-mini: Amigo
      url: /blog/friends
    -
      name:
        cmn: 异次元之旅 ☈
        en: Go Wild ☈
        tok: tawa suli ☈
        lzh: 雲闥 ☈
        dng: Йицыйүан җылү ☈
        art-x-mini: Savaje go ☈
      url: https://travel.moe/go.html
