url: https://matling.fit
baseurl: "/"
title: 物灵

show_excerpts: true
permalink: /blog/:title:output_ext
excerpt_separator: <!--more-->

plugins:
        - jekyll-paginate
        - jekyll-feed

paginate: 10
paginate_path: "/blog/:num"

theme-2038:
        drawer-links:
                -
                        name:
                                cmn: 博文
                                cmn-Latn: Bówén
                                en: Blog
                                tok: lipu ali
                                art-x-xdi8: wi8
                        url: /blog
                -
                        name: about
                        url: /blog/about
                -
                        name:
                                cmn: 他山
                                cmn-Latn: Tāshān
                                en: Friends
                                tok: jan pona
                        url: /friends
                



