base_url = "https://matling.fit"
title = "物灵"

compile_sass = true
generate_feeds = true
build_search_index = false

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
highlight_theme = "boron-modified"
highlight_code = true
extra_syntaxes_and_themes = ["boron-modified.tmTheme"]

[translations]
language_name = "English"
toc = "Contents"
btn_read = "Read more (LEN words)"
higher = "Previous"
lower = "Next"
skip_link = "Skip to Content"
other_languages = "Translations"
backlinks = "Backlinks"

[languages.zh]
title = "物灵"

[languages.cmn-arab]
title = "物灵"

[languages.tok]
title = "𐙞[⊕＞ń]"

[languages.ja]
title = "物霊"

[languages.ko]
title = "물령"

[languages.zh.translations]
language_name = "华语"
toc = "目次"
btn_read = "续读 (LEN 字)"
higher = "旧"
lower = "新"
skip_link = "跳至正文"
other_languages = "外文"
backlinks = "链入"

[languages.cmn-arab.translations]
language_name = "جࣨىُوً خُوَ"
toc = "مُلُ"
btn_read = "چَاْخاَدِ (کْ ىُو LEN زْ)"
higher = "لَوْ"
lower = "سٍ"
skip_link = "تِىَوْ کَىْش"
other_languages = "وَىلُ هُوَ"
backlinks = "زٍلَيْدِ"

[languages.ko.translations]
language_name = "한국어"
toc = "목차"
btn_read = "계속 읽기 (LEN 단어)"
higher = "옛"
lower = "새"
skip_link = "내용으로 건너뛰기"
other_languages = "외문"
backlinks = "역링크"

[languages.tok.translations]
language_name = "toki pona"
toc = "jo"
btn_read = "lipu ni (nimi LEN)"
higher = "pini"
lower = "kama"
skip_link = "tawa open lipu"
other_languages = "ante toki"
backlinks = "linja kama"

[languages.art-002.translations]
language_name = "Mini"
toc = "Peso"
btn_read = "Leje e mui (LEN name)"
higher = "ante"
lower = "afa"
skip_link = "go note-kapo"
other_languages = "Ota linga"
backlinks = "baka-liga"

[languages.art-001.translations]
language_name = "単亜語"
toc = "目次"
btn_read = "全文 (LEN個 字)"
higher = "前"
lower = "後"
skip_link = "文章之開始于"
other_languages = "外文"
backlinks = "連入"

[languages.ja.translations]
language_name = "日本語"
toc = "目次"
btn_read = "全文 (LEN 字)"
higher = "前"
lower = "後"
skip_link = "本文にスキップ"
other_languages = "外文"
backlinks = "被リンク"

[extra]

[[extra.t2038.drawer_links]]
url = "/blog"

  [extra.t2038.drawer_links.name]
  zh = "博文"
  lzh = "吟草"
  wuu = "步录"
  ko = "블로그"
  en = "Blog"
  tok = "lipu"
  dng = "Зуəвын"
  art-002 = "Note"
  art-001 = "文"
  cmn-arab = "ڤٌ"
  ja = "ブログ"

[[extra.t2038.drawer_links]]
url = "https://lex.matling.fit"

  [extra.t2038.drawer_links.name]
  zh = "含章字典"
  lzh = "含章字典"
  wuu = "含章字典"
  ko = "함장자전"
  en = "Lexicon"
  tok = "nimi Malin"
  dng = "Ханҗон хуадян"
  art-002 = "Buku-name"
  art-001 = "含章字典"
  cmn-arab = "خًجًنْ كتاب"
  ja = "含章字典"

[[extra.t2038.drawer_links]]
url = "/about/site"

  [extra.t2038.drawer_links.name]
  zh = "关于"
  lzh = "自敘"
  wuu = "关于"
  ko = "나에게"
  en = "About"
  tok = "mi seme"
  dng = "Сыйҗяди"
  art-002 = "Ego"
  art-001 = "自己紹介"
  cmn-arab = "أنا"
  ja = "につき"

[[extra.t2038.drawer_links]]
url = "/about/friends"

  [extra.t2038.drawer_links.name]
  zh = "地铁"
  lzh = "通軌"
  wuu = "地铁"
  ko = "전철"
  en = "Metro"
  tok = "jan pona"
  dng = "Тамыр"
  art-002 = "Unda-rela"
  art-001 = "電車"
  cmn-arab = "خوَباً"
  ja = "となり"